[external]
[external.directory]
type = "partial" # "partial" or "full"
path = "lib" # do not include './' here

[[external.libraries]]
name = "SDL2"
url = "https://github.com/libsdl-org/SDL/releases/download/release-{version}/SDL2-devel-{version}-{compiler}.zip"
versions = ['2.30.5']
license = ""
[external.libraries.MinGW]
compiler = "mingw"
[external.libraries.MinGW.x64]
directory = "SDL2-{version}/x86_64-w64-mingw32"
[external.libraries.MinGW.x86]
directory = "SDL2-{version}/i686-w64-mingw32"
[external.libraries.VisualStudio]
compiler = "VC"
include = "SDL2-{version}/include"
[external.libraries.VisualStudio.x64]
lib = "SDL2-{version}/lib/x64"
[external.libraries.VisualStudio.x86]
lib = "SDL2-{version}/lib/x86"

[[external.libraries]]
name = "SDL2_ttf"
url = "https://github.com/libsdl-org/SDL_ttf/releases/download/release-{version}/SDL2_ttf-devel-{version}-{compiler}.zip"
versions = ['2.22.0']
license = ""
[external.libraries.MinGW]
compiler = "mingw"
[external.libraries.MinGW.x64]
directory = "SDL2_ttf-{version}/x86_64-w64-mingw32"
[external.libraries.MinGW.x86]
directory = "SDL2_ttf-{version}/i686-w64-mingw32"
[external.libraries.VisualStudio]
compiler = "VC"
include = "SDL2_ttf-{version}/include"
[external.libraries.VisualStudio.x64]
lib = "SDL2_ttf-{version}/lib/x64"
[external.libraries.VisualStudio.x86]
lib = "SDL2_ttf-{version}/lib/x86"

[[external.libraries]]
name = "Vulkan"
url = "https://sdk.lunarg.com/sdk/download/{version}/{operating_system}/VulkanSDK-{version}-Installer.exe"
versions = ['1.3.283.0']
license = ""
