# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  CzenginePlusPlus_config = debug_win64

else ifeq ($(config),release_win64)
  CzenginePlusPlus_config = release_win64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := CzenginePlusPlus

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CzenginePlusPlus:
ifneq (,$(CzenginePlusPlus_config))
	@echo "==== Building CzenginePlusPlus ($(CzenginePlusPlus_config)) ===="
	@${MAKE} --no-print-directory -C . -f CzenginePlusPlus.make config=$(CzenginePlusPlus_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f CzenginePlusPlus.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  release_win64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CzenginePlusPlus"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"